name: CI (devcontainer)

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  packages: read

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run CI in devcontainer (no push)
        uses: devcontainers/ci@v0.3
        with:
          configFile: .devcontainer/devcontainer.json
          push: never
          runCmd: |
            rustup show
            rustup target list --installed
            make check
            make test
            make build-arm
            TARGET=aarch64-unknown-linux-gnu MODE=release ./scripts/run-emu.sh